version: 0.0
os: linux
files:
  - source: /
    destination: /webapps/carwings
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      runas: root
  ApplicationStop:
    - location: scripts/application_stop.sh
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      runas: root
